spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: admin
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true
      show_sql: true
      dialect: org.hibernate.dialect.H2Dialect
